name: Create-PR

# Run this workflow every time there's a new push into staging
on:
  push:
    branches: [ staging ]
    
    jobs:
      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@v2.3
        with:
          # Branch name to pull from, default is triggered branch
          source_branch: ${{ github.base_ref }}
          # Branch name to sync to in this repo, default is master
          destination_branch: master
          # Pull request title
          pr_title: ${{ github.event.pull_request.title }}
          # Pull request body
          pr_body: Testing pr creating upon pr into staging
          # Pull request assignees, comma-separated list (no spaces)
          pr_assignee: ${{ github.event.pull_request.assignee }}
          # GitHub token secret
          github_token: ${{ secrets.GITHUB_TOKEN }}
          if: ${{ github.event_name }} == 'pull_reqeust'