name: Create-PR

# Run this workflow every time there's a new push into staging
on:
  pull_request:
    types: [ closed ]
    branches: [ staging ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == true
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out a copy of repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@v2.3
        with:
          # Branch name to pull from, default is triggered branch
          source_branch: ${{ github.event.pull_request.head.ref }}
          # Branch name to sync to in this repo, default is master
          destination_branch: master
          # Pull request title
          pr_title: ${{ github.event.pull_request.title }}
          # Pull request body
          pr_body: ${{ github.event.pull_request.body }}
          # Pull request assignees, comma-separated list (no spaces)
          pr_assignee: ${{ github.event.pull_request.assignee }}
          # GitHub token secret
          github_token: ${{ secrets.GITHUB_TOKEN }}